import { Injectable } from "@angular/core";


@Injectable({
  providedIn: 'root'
})

export class med {
  medData={

    //2em visite prise en charge sp=second prise en charge
    'If_VicWasSeronegaGotPepINSeventyTwoSp':'oui',
    'CommentVicWasSeronegaGotPepINSp':'pas de commentaire',
    'If_VicGotPepBecomeSeropoAfterTreeMonthSp':'oui',
    'CommentVicGotPepBecomeSeropoAfterTreeMonthSp':'pas de commentaire',
    'If_VicGotTreatAgainsIstTesLaboPosiSp':'oui',
    'CommentVicGotTreatAgainsIstTesLaboPosiSp':'pas de commentaire',
    'If_VicWasPregnantINviolFakeCoucheSp':'non',
    'CommentVicWasPregnantINviolFakeCoucheSp':'pas de commentaire',
    'If_VicGotFistuleWasReparedSp':'non',
    'CommentVicGotFistuleWasReparedSp':'pas de commentaire',
    'ObservationsSp':'pas de commentaire',
    'DateVisiTeSp':'20/10/2020',
    'PartenaireRespoSp':'hope',
    //#reference medicale
    'Date':'20/20/2022',
    'GotAssMedical':'oui',
    'TypeAssystanceGot':'types assystances',
   // #Examens
    'ExamenTestGrossesse':'oui',
    'ExamenTestVih':'oui',
    'ExamenTestIst':'oui',
    'ExamenPhysique':'oui',
    'ExamenLabo':'oui',
    'If_AssisanceWrittenDoc':'oui',
    'RapportMedical':'oui',
    'AttestationMedical':'oui',
   // #traitement
    'TrContracepUrgence':'oui',
    'TrPreventionVih':'oui',
    'TrIst':'oui',
    'TrOtherPricise':'oui',
    'CertificaMedical':'oui',
    'If_ExamenMedicauxAfterAgression':'oui',
    'ExamenMediAfterAgressionDescript':'oui',
    'ExamenMediAfterAgressionReasonsIfnon':'oui',
    'If_GrossesseBeforeViol':'oui',
    'If_ConceptionSviol':'oui',
    'IF_EnfantOrFoetusalive':'non',
    'SequellOrLesionPhysique':'oui',
    'NomStructure':'goma',
    'QualiteStrucutre':'ps',
    'NomClinicien':'schadrack',
    'FonctionClinicien':'medecin',
    'DateClini':'20/12/2020',
    'SignatureClini':'signature',
    'if_victime_got_pep_kit_became_seropositive_after_one_month':'oui',
    '2p_if_victim_was_seronegative_got_pep_inseventytwo_hours':'oui',
    'if_ist_test_positif_after_onemoth':'oui','if_ist_test_negatif_after_onemoth':'oui',
    'if_ist_test_positif_after_inseventytwo_hours':'oui',
    'if_ist_test_negatif_after_inseventytwo_hours':'oui',
    'if_vih_test_negatif_after_inseventytwo_hours':'oui',
    'if_vih_test_positi_after_inseventytwo_hours':'oui',
    'if_vih_test_positiffafter_onemoth':'oui','if_vih_test_negatiffafter_onemoth':'oui',
    'if_vacccination_against_hepatib':'non', 'vacccination_against_hepatib_remark':'remarques',
    'if_other_frature_treated':'oui', 'other_frature_treated_remark':'remark',
    'if_injure_treatement':'oui','injure_treatement_remark':'remarques',
    'if_contraception_emergency':'oui','contraception_emergency_remark':'remarques',
    'if_tratement_preventionist':'oui','tratement_preventionist_remarques':'remarques',
    'if_prevention':'oui','prevention_remarque':'remarques',
    'imageri_medical_result':'well','if_other_testexam':'oui','other_testexam_result':'well',
    'if_imageri_medical':'oui',
    'if_test_hepa_b':'oui','test_hepa_b_resultat':'well',
    'vih_result':'well',
    'if_rpr_vdrl_test':'oui','rpr_vdrl_test_result':'well',
    'pregnacy_result':'bien ',
    'if_cicatrice':'oui',
    'victime_sexe':'m',
    'breathin_frequency':'12',
    'cardiaque_frequency':'12',
    'temperature':'12','if_poul':'oui',
    'if_status_vaccinal_inconnu':'oui',
    'if_status_vih_not_vaccinate':'oui',
    'if_status_vih_vaccinate':'oui',
    'status_vih_vaccinate_date':'12/12/2022',
    'tetanos_statusvaccinal_notknown':'oui','date':'20/10/2022',
    'reference_date':'20/12/2020',
    'if_victim_got_istVih_treatement':'oui','victim_got_istVih_treatement_comment':'pas de commentaire',
    'if_alcool_taken_everyday_agression':'oui','if_medicins_taken_everyday_agression':'non','if_drug_take_everyday_agression':'non',
    'if_alcool_taken_after_agression':'oui','if_medicins_taken_after_agression':'oui','if_drug_take_after_agression':'oui',
    'if_alcool_taken_before_agression':'oui','if_medicins_taken_before_agression':'oui','if_drug_take_before_agression':'oui',
     'if_allergy_known':'oui',
     'if_last_date_of_regle':'oui','if_last_date_of_regle_notsure':'non','last_date_of_regle_comment':'pas de commentaire',
    'if_regle_during_agression':'oui','if_regle_during_agression_notsure':'oui','regle_during_agression_comment':'pas de commentaire',
    'if_other_contra':'oui','if_other_contra_notsure':'oui','other_contra_comment':'pas de comentaire',
     'if_injection_contra':'oui','if_injection_contra_notsure':'oui','injection_contra_comment':'pas de commentaire',
    'if_sterille_contra':'oui','if_sterille_notsure_contra':'oui','sterille_comment_contra':'pas de commentaire',
    'if_contra_pillule':'oui','contra_pillule_notsure':'oui','contra_pillule_comment':'pas de commentaire',
    'contraception_comment':'pas de commentaire',
    'if_contraception_notsure':'oui',
    'if_sexe_volontary_in_agression':'oui',
    'if_defeque':'oui',
    'if_urinate_sign':'oui','if_other_ejac':'oui','if_other_ejac_notsure':'oui','other_ejac_comment':'pas de commentaire',
    'if_ejac_anus_notsure':'oui',
    'if_ejac_vagin_notsure':'non','ejacu_vagin_comment':'pas de commentaire','if_ejac_mouth_notsure':'oui','ejac_mouth_comment':'pas de commentaire','if_ejacul':'non','if_ejac_notsure':'oui','ejaculation_comment':'pas de commentaire',
    'if_other_orifice_penetration':'oui','if_other_orifice_penetration_notsure':'oui',
    'if_anus_orifice_notsure':'oui','anus_orifice_comment':'pas de commentaire',
    'other_orifice_penetration_comment':'pas de commentaire',
    'if_vagin_orifice_notsure':'oui','mouth_orifice_comment':'pas de commentaire','mouth_orifice_notsure':'oui', 'orifice_penetration_notsure':'oui','orifice_penetration_comment':'oui','if_orifice_penetration':'oui',
    'if_other_penetration':'oui','other_penetration_notsure':'oui','other_penetration_comment':'pas de commentaire','finger_penetration_notsure':'oui','notion_contrainte':'armes blanche','if_family_member':'oui','penis_penetration_notsure':'oui','penetration_comment':'choker','penetration_not_sure':'oui','is_victime_intimidate':'oui','if_neighbour':'Non','violence_types':'chemin de l ecole','if_connaissance':'oui','are_militaries': 'oui', 'known_by_victim': 'non','age_authors':'30', 'sex_of_authors': 'Hommes', 'description_of_authors': 'Agites',
'kind_of_relationship_with_victim': 'aucun', 'is_the_victim_afraid_to_go_home': 'oui', 'date_of_agression': '23/12/2022 12:12:23',
 'time_of_agression': '12:00', 'numbers_of_rapes': '1', 'description_of_circonstances': 'Chemin ecole',
  'description_of_rape': 'Chemin ecole', 'pillage': 'oui', 'others_witnesses': 'oui', 'if_penetration': 'non',
  'agression_comment': 'Dificlie', 'if_penis_penetration': 'oui', 'penis_penetration_comment': 'Pas de commentaire',
  'if_finger_penetration': 'oui', 'finger_penetration_comment': 'Pas de commentaire', 'if_penetration_with_other_things': 'oui',
   'other_things_penetration_comment': 'Pas de comment', 'if_mouth_orifice': 'oui', 'if_vagin_orifice': 'oui',
   'vagin_orifice_comment': 'pas de commentaire', 'if_anus_orifice': 'oui', 'if_other_orifice': 'Oui', 'other_orifice_comment': 'Oui',
   'if_ejac_in_mouth': 'non', 'ejac_in_mouth_comment': 'Oui', 'if_ejac_vagin': 'non', 'ejac_vagin_comment': 'Oui', 'if_ejac_anus': 'oui',
   'ejac_anus_comment': 'no comment', 'if_ejac_other': 'Oui', 'ejac_other_comment': 'Oui', 'if_used_Condom': 'oui', 'condom_use_comment': 'pas de commentaire','used_condom_notsure':'oui', 'age': 26,
   'adress': 'Himbi', 'zone': 'Goma', 'sex': 'Feminin', 'place_of_birth': 'Goma',
    'marital_status': 'Reinsertion socio-economique', 'date_of_examination': '2021-10-29T22:00:00.000Z', 'level_of_studies': 'Professeur',
    'helper_name': 'Bahati', 'occupation': 'Medecin', 'if_vomit_sign': 'Oui', 'vomit_sign_comment': 'Oui', 'if_Sign_of_pee': 'Oui',
    'sign_of_pee_comment': 'Oui', 'if_sign_poo': 'Oui', 'poo_sign_comment': 'Oui', 'if_Clothes_Changed': 'Oui', 'clothes_Changed_comment': 'Oui',
    'if_bath_taken': 'Oui', 'bath_taken_comment': 'Oui', 'if_brushed_teeth': 'Oui', 'brushed_teeth_comment': 'Oui', 'if_had_volontary_sex': 'Oui',
    'if_had_volontary_sex_comment': 'Oui', 'last_volontary_sex_date': '23/12/2022', 'last_hour_volontary_sex': '12:12', 'if_contraception': 'Oui',
      'if_mutilation_notsure':'oui','if_mutilation': 'oui', 'mutilation_comment': 'pas de commentaire', 'mutilation_hisory_and_type': 'Oui',
     'if_menstruation_during_rape': 'Oui', 'menstruation_in_rape_comment': 'Oui','bleed_during_agression_comment':'pas de commentaire','if_bleed_during_agression_notsure':'oui' ,'if_bleed_during_agression': 'oui',
      'if_parity': 'oui', 'if_gesity': 'oui', 'if_abortion': 'non', 'if_dead': 'oui',
      'existing_health_problems': 'oui', 'before_agression': 'Oui', 'after_agression': 'Oui', 'regular_habit': 'Oui',
      'if_tetanos_vaccin': 'Oui', 'if_tetanos_no_vaccinate':'oui','tetanos_vaccin_date': '20/20/2022', 'if_hepatit_b_vaccin': 'Oui', 'hepatit_b_vaccin_date': 'Oui', 'vih_status': 'Oui',
      'victim_appearance': 'cheveux', 'victim_psycho_aspects': 'peurs', 'victim_weight': '12', 'victim_height': '1', 'victim_ta_sign': 'Oui',
      'bleeding_wound': 'Oui','bleeding_wound_part':'vendre','cicatrice_part':'fesse' ,'state_of_head': 'bon', 'state_of_nose': 'Oui', 'eyes_state': 'Oui', 'mouth_state': 'Oui', 'ears_state': 'Oui',
       'neck_state': 'Oui', 'chest_state': 'Oui', 'back_state': 'Oui', 'abdomen_state': 'Oui','battocks_state':'oui', 'upper_menbers_state': 'Oui', 'lower_menbers_state': 'Oui',
        'deus_presence': 'oui', 'conjoctives_presence': 'oui', 'presence_behind_ears': 'oui', 'victim_postion_genital_exam': 'Oui',
        'victim_position_anal_exam': 'Oui', 'description_of_all_pains': 'ALL WE NEED', 'exam': 'Oui', 'echantillon': 'Oui', 'description_of_proof': 'Oui',
        'examination_place': 'Oui', 'storage_place': 'Oui', 'test_set_date': 'Oui', 'if_vih_prevention': 'Oui', 'vih_prevention_comment': 'Oui',
        'if_ist_prevention': 'Oui', 'ist_prevention_comment': 'Oui', 'if_contraception_urgent': 'Oui', 
        'if_wound_treatment': 'Oui', 'wound_treatment_comment': 'Oui', 'if_prophylaxy_treatment': 'oui', 'prophylaxy_treatment_remark': 'remarques',
         'if_hepatite_not_vaccinated': 'Oui','if_hepatite_statusvaccin_notknown':'oui', 'hepatite_vaccin_date': '12/12/2022', 'if_fustile_treatment': 'Oui', 'fustile_treatment_comment': 'Oui',
         'if_other_treatement': 'Oui', 'other_treatement_comment': 'Oui', 'general_psycho_state': 'Oui', 'if_victim_plan_to_report_agression': 'Oui',
          'if_victim_has_safe_place': 'Oui', 'if_victim_has_carring_person': 'Oui', 'name_of_responsible_partner': 'Oui', 'advises_given': 'Oui',
          'reference_type': 'Oui', 'reference_structure': 'Oui', 'date_of_reference': 'Oui', 'references_comment': 'Oui', 'references_conclusion': 'Oui',
           'nom_clinicien':'hope','recommandation_rendez_vous': 'Oui', 'structure_name': 'Oui', 'structure_phone_number': 'Oui', 'structure_physical_adress': 'Oui',
           'structure_comment':'pas de commentaire','health_zone_structure': 'Oui', 'date_of_exam': '09/04/200', 'if_positive_regnancy_test_pafter_72h': 'Oui',
           'if_negative_pregnecy_test_after_72h': 'Oui', 'if_positive_pregnecy_test_after_month': 'Oui', 'if_negative_pregnecy_test_after_month': 'Oui',
            'if_positive_vih_test_after_72h': 'Oui', 'if_negative_vih_test_after_72h': 'Oui', 'if_positive_vih_test_after_month': 'Oui',
            'if_negative_vih_test_after_month': 'Oui', 'if_positive_ist_test_after_72h': 'Oui', 'if_negative_ist_test_after_72h': 'Oui',
            'if_positive_ist_test_after_month': 'Oui', 'if_negative_ist_test_after_month': 'Oui',
            'if_victim_sero_negative_got_Pep_after_rape_or_why_not': 'oui', 'if_victim_sero_negative_got_Pep_after_rape_comment': 'Oui',
            'comment_victim_got_pep_become_sero_positive_after_one_month':'pas de commentaire','if_victim_got_pep_become_sero_positive_after_one_month': 'non', 'victim_got_pep_become_sero_positive_after_one_month_comment': 'pas de commentaire',
            'if_victim_got_other_ist_treatment': 'Oui', 'victim_got_other_ist_treatment_comment': 'Oui', 'if_victim_pregnant_during_rape': 'non',
             'victim_pregnant_during_rape_comment': 'Oui', 'if_victim_got_fistule_and_treated': 'oui', 'victim_got_fistule_and_treated_remark': 'Oui',
             'observation_comment': 'Oui', 'visit_date': '20/20/2020', 'responsible_partner': 'hope', 'if_got_medical_assistance': 'Oui',
             'date_of_assistance': 'Oui','date_of_birth':'1999','town_of_birth':'goma', 'type_of_assistance': 'Oui', 'if_pregnancy_test_positifafter_sevenytwohours': 'Oui', 'if_vih_test': 'Oui', 'if_ist_test': 'Oui',
              'if_physical_exam': 'Oui', 'if_labo_exam': 'Oui', 'if_medical_report': 'Oui', 'if_medical_attestation': 'Oui','if_pregnancy_test_negatiffafter_sevenytwohours':'oui',
              'document_of_assistance': 'Oui', 'if_contraception_is_urgent': 'Oui', 'if_Vih_prevention': 'Oui', 'if_ist_treatement': 'Oui','if_pregnancy_test_negatiffafter_onemoth':'oui','if_pregnancy_test_positiffafter_onemoth':'oui',
              'other_treatement': 'Oui', 'medical_certitificate': 'Oui', 'other_medical_certitificate': 'Oui', 'if_medical_exam_done_after_viol': 'Oui',
               'medical_exam_done_after_viol_comment': 'Oui', 'if_pregnacy_before_rape': 'Oui', 'if_conception_after_rape': 'Oui',
               'if_child_alive_and_healthy': 'Oui', 'physical_lesions': 'Oui', 'structure_quality': 'Oui', 'certificate_souscription': 'Oui',
               'certificate_function': 'Oui', 'certificate_date_examination': 'Oui', 'certificate_owner': 'Oui', 'certificate_owner_bith_date': 'Oui',
               'age_of_owner_not_known': 'Oui', 'place_of_demand': 'Oui', 'sex_of_owner': 'Oui', 'owner_adresss': 'Oui', 'victim_date_of_agression': 'Oui',
                'message_of_helper': 'Oui', 'owner_signs': 'Oui', 'general_physical_exam_1': 'Oui', 'general_physic_exam': 'Oui', 'para_din_examen': 'Oui',
                'risk_evaluation': 'Oui','number_of_witness':'4','civillians':'oui',
                'clinicien_fuction':'post','names_accompagnateurs': 'cia,hope,claude','unknown':'oui', 'victim_sate': 'Oui', 'pronostic': 'Oui', 'conduite': 'Oui', 'conclusion': 'Oui','provenance':'katindo','marital_state':'celibataire'}

                data(){
                  return this.medData;
                }


}
