# Generated by Django 3.2.10 on 2022-01-04 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_patients_photo'),
        ('medicaldata', '0002_consentemendata_id_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychoinfodata',
            name='id_patient',
            field=models.OneToOneField(default=int, on_delete=django.db.models.deletion.CASCADE, to='accounts.patients'),
            preserve_default=False,
        ),
    ]
