from django.db import models
from django.db.models.deletion import CASCADE

from accounts.models import patients

# Create your models here.
class AuthorsProfile(models.Model):
    #profils du presumer auteur
    Id_authors=models.AutoField(primary_key=True)
    Id_patient=models.OneToOneField(patients,on_delete=CASCADE)
    NombreAgresseurs=models.IntegerField(null=True)
    If_PersoWithWeapons=models.BooleanField(default=False,null=True) 
    If_Civil=models.BooleanField(default=False,null=True) 
    If_Inconnu=models.BooleanField(default=False,null=True) 
    AgeAuteurs=models.IntegerField(null=True)
    SexeAuteurs=models.CharField(max_length=200)
    DesCriptionPhysique=models.TextField(max_length=800)
    If_RelationWithVictimes=models.BooleanField(default=False,null=True)
    If_FamilyMember=models.BooleanField(default=False,null=True)
    If_neigbour=models.BooleanField(default=False,null=True)
    If_connaissance=models.BooleanField(default=False,null=True)
    autherR=models.CharField(max_length=200)
    #Evaluation du risque
    If_AfraidBackofHome=models.BooleanField(default=False,null=True)
    If_IntimidateDeath=models.BooleanField(default=False,null=True)
    #Agression
    DateAgression=models.DateField()
    TimeAgression=models.DateTimeField()
    NumberIncidentVictime=models.IntegerField()
    DescriptionAgressionB=models.TextField(max_length=800)
    Circonstance=models.CharField(max_length=200)
    ViolenceType=models.CharField(max_length=200)
    If_Pillage=models.CharField(max_length=200)
    NotionContrainte=models.CharField(max_length=200)
    OtherPresentVicNumber=models.IntegerField()

class LorsAgressionPage(models.Model):
    #lors agression
    Id_medTimeAgression=models.AutoField(primary_key=True)
    Id_patient=models.OneToOneField(patients,on_delete=CASCADE)
    #penetration
    Penetration=models.BooleanField(default=False,null=True)
    Penetrationnotsure=models.BooleanField(default=False,null=True)
    PenetrationComment=models.TextField(max_length=500)
    PenePenis=models.BooleanField(default=False,null=True)
    PenePenisPasSur=models.BooleanField(default=False,null=True)
    PenePenisComment=models.TextField(max_length=500,null=True)
    PeneDoigt=models.BooleanField(default=False,null=True)
    PeneDoigtPasSur=models.BooleanField(default=False,null=True)
    PeneDoigtComment=models.TextField(max_length=500,null=True)
    PeneOtherDescription=models.BooleanField(default=False,null=True)
    PeneOtherDescriptionPasSur=models.BooleanField(default=False,null=True)
    PeneOtherDescriptionComment=models.TextField(max_length=500,null=True)
    #orifices de penetration
    OrificesPene=models.BooleanField(default=False,null=True)
    OrificesPenePasSur=models.BooleanField(default=False,null=True)
    OrificesPeneComment=models.TextField(max_length=500,null=True)
    OrificeBouche=models.BooleanField(default=False,null=True)
    OrificeBouchePasSur=models.BooleanField(default=False,null=True)
    OrificeBoucheComment=models.TextField(max_length=500,null=True)
    OrificeVagin=models.BooleanField(default=False,null=True)
    OrificeVaginPasSur=models.BooleanField(default=False,null=True)
    OrificeVaginComment=models.TextField(max_length=500,null=True)
    OrificeAnus=models.BooleanField(default=False,null=True)
    OrificeAnusPasSur=models.BooleanField(default=False,null=True)
    OrificeAnusComment=models.TextField(max_length=500,null=True)
    OrificeOtherDescription=models.BooleanField(default=False,null=True)
    OrificeOtherPasSurDescrption=models.BooleanField(default=False,null=True)
    OrificeOtherCommentDescription=models.TextField(max_length=500,null=True)
    #ejaclation
    Ejaculation=models.BooleanField(default=False,null=True)
    EjaculationPasSur=models.BooleanField(default=False,null=True)
    EjaculationComment=models.TextField(max_length=500,null=True)
    EjacBouche=models.BooleanField(default=False,null=True)
    EjacBouchePasSur=models.BooleanField(default=False,null=True)
    EjacBoucheComment=models.TextField(max_length=500,null=True)
    EjacVagin=models.BooleanField(default=False,null=True)
    EjacVaginPasSur=models.BooleanField(default=False,null=True)
    EjacVaginComment=models.TextField(max_length=500,null=True)
    EjacAnus=models.BooleanField(default=False,null=True)
    EjacAnusPasSur=models.BooleanField(default=False,null=True)
    EjacAnusComment=models.TextField(max_length=500)
    EjacOther=models.BooleanField(default=False,null=True)
    EjacOtherPasSur=models.BooleanField(default=False,null=True)
    EjacOtherComment=models.TextField(max_length=500)
    USageCondomn=models.BooleanField(default=False,null=True)
    USageCondomnPasSur=models.BooleanField(default=False,null=True)
    USageCondomnComment=models.TextField(max_length=500)
    Vomi=models.BooleanField(default=False,null=True)
    Urine=models.BooleanField(default=False,null=True)
    Defeque=models.BooleanField(default=False,null=True)
    VetementChanged=models.BooleanField(default=False,null=True)
    TakeBirth=models.BooleanField(default=False,null=True)
    BrushTeethORmouch=models.BooleanField(default=False,null=True)
    If_rapportSexuelVolotaire=models.BooleanField(default=False,null=True)
    LastDateRapportSexuel=models.DateField()
    LastHourRapportSexuel=models.TimeField()
class AntecedentVictim(models.Model):
    #antecedent de la victime
    Id_AntMed=models.AutoField(primary_key=True)
    Id_patient=models.OneToOneField(patients,on_delete=CASCADE)
    Contraception=models.BooleanField(default=False,null=True)
    ContraceptionPasSur=models.BooleanField(default=False,null=True)
    ContraceptionComment=models.TextField(max_length=500) 
    ContracePilule=models.BooleanField(default=False,null=True)
    ContracePilulePasSur=models.BooleanField(default=False,null=True)
    ContracePiluleComment=models.TextField(max_length=500) 
    ContraceSterilet=models.BooleanField(default=False,null=True)
    ContraceSteriletPasSur=models.BooleanField(default=False,null=True)
    ContraceSteriletComment=models.TextField(max_length=500) 
    ContraceInjection=models.BooleanField(default=False,null=True)
    ContraceInjectionPasSur=models.BooleanField(default=False,null=True)
    ContraceInjectionComment=models.TextField(max_length=500)
    ContraceOtherForspecify=models.BooleanField(default=False,null=True)
    ContraceOtherForspecify=models.BooleanField(default=False,null=True)
    ContraceOtherForspecifyComment=models.TextField(max_length=500)
    Mutilation=models.BooleanField(default=False,null=True)
    MutilationPasSur=models.BooleanField(default=False,null=True)
    MutilationComment=models.TextField(max_length=500)
    IF_MutilationHistoricType=models.TextField(max_length=500,blank=True,null=True)
    If_DateLastRegles=models.DateField()
    If_DateLastReglesPasSur=models.BooleanField(default=False,null=True)
    DateLastReglesComment=models.TextField(max_length=500)
    If_RegleDuringAgression=models.BooleanField(default=False,null=True)
    If_RegleDuringAgressionPasSur=models.BooleanField(default=False,null=True)
    RegleDuringAgressionComment=models.BooleanField(default=False,null=True)
    If_BleedDuringAgression=models.BooleanField(default=False,null=True)
    If_BleedDuringAgressionPasSur=models.BooleanField(default=False,null=True)
    BleedDuringAgressionComment=models.BooleanField(default=False,null=True)
    Parite=models.BooleanField(default=False,null=True)
    Gestite=models.BooleanField(default=False,null=True)
    Avortement=models.BooleanField(default=False,null=True)
    Deces=models.BooleanField(default=False,null=True)
    ProblemesSanteExistant=models.TextField(max_length=500)
    AlergisConnu=models.TextField(max_length=500)
    TookAlcoolBeforeAgression=models.BooleanField(default=False,null=True)
    TookAlcoolAfterAgression=models.BooleanField(default=False,null=True)
    TookAlcoolofthenAgression=models.BooleanField(default=False,null=True)
    TookMedicinsBeforeAgression=models.BooleanField(default=False,null=True)
    TookMedicinsAfterAgression=models.BooleanField(default=False,null=True)
    TookMedicinsofthenAgression=models.BooleanField(default=False,null=True)
    TookDragsBeforeAgression=models.BooleanField(default=False,null=True)
    TookDragssAfterAgression=models.BooleanField(default=False,null=True)
    TookDragssofthenAgression=models.BooleanField(default=False,null=True)

class StatusVaccinalPage(models.Model):
#status vaccinal
    Id_statut=models.AutoField(primary_key=True)
    Id_patient=models.OneToOneField(patients,on_delete=CASCADE)
    TetanosVaccine=models.BooleanField(default=False,null=True)
    TetanosDateVaccination=models.DateField()
    TetanosStatusVaccinalInconnu=models.BooleanField(default=False,null=True)
    HepatiteBVaccine=models.BooleanField(default=False,null=True)
    HepatiteBDateVaccination=models.DateField()
    HepatiteBStatusVaccinalInconnu=models.BooleanField(default=False,null=True)
    StatusVihVaccine=models.BooleanField(default=False,null=True)
    StatusVihDateVaccination=models.DateField()
    StatusVihStatusVaccinalInconnu=models.BooleanField(default=False,null=True)
    ApparenceVictime=models.TextField(max_length=500)
    AspectPsychoVict=models.TextField(max_length=500)
    SignesVitaux=models.CharField(max_length=200)
    Poids=models.IntegerField()
    Taille=models.FloatField()
    Ta=models.FloatField()
    pouls=models.IntegerField()
    Temperature=models.FloatField()
    FrequenceRespiratoire=models.FloatField()
    FrequenceCardiaque=models.FloatField()
    PlaisSaignent=models.BooleanField(default=False,null=True)
    PlaisSaignentPartie=models.TextField(max_length=300)
    Cicatrice=models.BooleanField(default=False,null=True)
    CicatriceSaignentPartie=models.TextField(max_length=300)
    EtatTete=models.BooleanField(default=False,null=True)
    EtatYeux=models.BooleanField(default=False,null=True)
    EtatOreilles=models.BooleanField(default=False,null=True)
    EtatPoitrine=models.BooleanField(default=False,null=True)
    EtatDos=models.BooleanField(default=False,null=True)
    EtatMembreSuperieure=models.BooleanField(default=False,null=True)
    EtatNez=models.BooleanField(default=False,null=True)
    EtatBouche=models.BooleanField(default=False,null=True)
    EtatCou=models.BooleanField(default=False,null=True)
    EtatAbdomen=models.BooleanField(default=False,null=True)
    EtatFesses=models.BooleanField(default=False,null=True)
    EtatMembreInferieure=models.BooleanField(default=False,null=True)
    VulvePerineScrotum=models.CharField(max_length=200)
    Hymen=models.CharField(max_length=200)
    Anus=models.CharField(max_length=200)
    VaginAndPenis=models.CharField(max_length=200)
    PositionPatienEnExamenGenital=models.CharField(max_length=200)
    DecubitusDorsalGenitalP=models.CharField(max_length=200)
    DecubitusVentralGenitalP=models.CharField(max_length=200)
    GenouPectoralGenitalP=models.CharField(max_length=200)
    DecubitusLateralGenitalP=models.CharField(max_length=200)
    PositionPatienEnExamenAnalP=models.CharField(max_length=200)
    DecubitusDorsalAnalP=models.CharField(max_length=200)
    DecubitusVentralAnalP=models.CharField(max_length=200)
    GenouPectoralAnalP=models.CharField(max_length=200)
    DecubitusLateralAnalP=models.CharField(max_length=200)
    DescriptionEndroitPlaiesLesion=models.TextField(max_length=200)

class TestExamenTraitement(models.Model):
    #testExamen&traitement
    Id_testExam=models.AutoField(primary_key=True)
    Id_patient=models.OneToOneField(patients,on_delete=CASCADE)
    GrossesseEchantillon=models.CharField(max_length=200)
    GrossesseResultat=models.CharField(max_length=200)
    VihEchantillon=models.CharField(max_length=200)
    VihResultat=models.CharField(max_length=200)
    RprVdrlEchantillon=models.CharField(max_length=200)
    RprVdrlResultat=models.CharField(max_length=200)
    BePbEchantillon=models.CharField(max_length=200)
    RprVdrlResultat=models.CharField(max_length=200)
    ImagerieMedicalEchantillon=models.CharField(max_length=200)
    ImagerieMedicalResultat=models.CharField(max_length=200)
    AutresEchantillon=models.CharField(max_length=200)
    AutresResultat=models.CharField(max_length=200)
    TypesPreuvesSites=models.TextField(max_length=500)
    LieuExamen=models.CharField(max_length=200)
    LieuStockage=models.CharField(max_length=200)
    preleverParDate=models.BooleanField(default=True)
    #traitement
    If_PreventionVih=models.BooleanField(default=False,null=True)
    PreventionVihComment=models.TextField(max_length=400)
    If_TraitementPreventIST=models.BooleanField(default=False,null=True)
    TraitementPreventISTComment=models.TextField(max_length=400)
    If_ContraceptionUrgence=models.BooleanField(default=False,null=True)
    ContraceptionUrgenceComment=models.TextField(max_length=400)
    If_TraitementBlessure=models.BooleanField(default=False,null=True)
    TraitementBlessureComment=models.TextField(max_length=400)
    If_ProfilaxyTetanos=models.BooleanField(default=False,null=True)
    ProfilaxyTetanosComment=models.TextField(max_length=400)
    If_VaccinationHepatiteB=models.BooleanField(default=False,null=True)
    VaccinationHepatiteBComment=models.TextField(max_length=400)
    If_reperationFistule=models.BooleanField(default=False,null=True)
    reperationFistuleComment=models.TextField(max_length=400)
    OtherTreatement=models.BooleanField(default=False,null=True)
    OtherTreatementComment=models.TextField(max_length=400)
    EtatPsychologiqueGen=models.TextField(max_length=400)
    If_VichasRightPlaceStay=models.BooleanField(default=False,null=True)
    If_VicHasPersonAccompany=models.BooleanField(default=False,null=True)
    NomPartenaireRespo=models.CharField(max_length=200)
    CouncilGiven=models.TextField(max_length=400)
    typerefernces=models.CharField(max_length=200)
    VoletStructReference=models.CharField(max_length=200)
    DateReference=models.DateField()
    Conclusion=models.TextField(max_length=400)
    SuiviRecoRendezVous=models.TextField(max_length=400)
    NomStructure=models.CharField(max_length=200)
    ContactStructure=models.CharField(max_length=20)
    AdresssePhysiStructure=models.CharField(max_length=200)
    ZoneDesante=models.CharField(max_length=200)
    nomClinicienMED=models.CharField(max_length=200)
    fonctionClinieMed=models.CharField(max_length=200)
    Date=models.DateField()
    Signature=models.CharField(max_length=200)

class MedExamAllPriseCharge(models.Model):
    #pages avec des images
    Id_medExamAllPC=models.AutoField(primary_key=True)
    Id_patient=models.OneToOneField(patients,on_delete=CASCADE)
    Date=models.DateField()
    #examens
    GrossesseExamenSeventyTwoAfterViol=models.BooleanField(default=False,null=True)
    GrossesseExamenOneMothAfterViol=models.BooleanField(default=False,null=True)
    VihExamenSeventyTwoAfterViol=models.BooleanField(default=False,null=True)
    VihssesseExamenOneMothAfterViol=models.BooleanField(default=False,null=True)
    IstExamenSeventyTwoAfterViol=models.BooleanField(default=False,null=True)
    IstssesseExamenOneMothAfterViol=models.BooleanField(default=False,null=True)
    #prise en charge
    If_VicWasSeronegaGotPepINSeventyTwo=models.BooleanField(default=False,null=True)
    CommentVicWasSeronegaGotPepIN=models.TextField(max_length=400)
    If_VicGotPepBecomeSeropoAfterOneMonth=models.BooleanField(default=False,null=True)
    CommentVicGotPepBecomeSeropoAfterOneMonth=models.TextField(max_length=400)
    If_VicGotTreatAgainsIstTesLaboPosi=models.BooleanField(default=False,null=True)
    CommentVicGotTreatAgainsIstTesLaboPosi=models.TextField(max_length=400)
    If_VicWasPregnantINviolFakeCouche=models.BooleanField(default=False,null=True)
    CommentVicWasPregnantINviolFakeCouche=models.TextField(max_length=400)
    If_VicGotFistuleWasRepared=models.BooleanField(default=False,null=True)
    CommentVicGotFistuleWasRepared=models.TextField(max_length=400)
    Observations=models.BooleanField(default=False,null=True)
    DateVisiTe=models.DateField()
    PartenaireRespo=models.CharField(max_length=200)

    #2em visite prise en charge sp=second prise en charge
    If_VicWasSeronegaGotPepINSeventyTwoSp=models.BooleanField(default=False,null=True)
    CommentVicWasSeronegaGotPepINSp=models.TextField(max_length=400)
    If_VicGotPepBecomeSeropoAfterTreeMonthSp=models.BooleanField(default=False,null=True)
    CommentVicGotPepBecomeSeropoAfterTreeMonthSp=models.TextField(max_length=400)
    If_VicGotTreatAgainsIstTesLaboPosiSp=models.BooleanField(default=False,null=True)
    CommentVicGotTreatAgainsIstTesLaboPosiSp=models.TextField(max_length=400)
    If_VicWasPregnantINviolFakeCoucheSp=models.BooleanField(default=False,null=True)
    CommentVicWasPregnantINviolFakeCoucheSp=models.TextField(max_length=400)
    If_VicGotFistuleWasReparedSp=models.BooleanField(default=False,null=True)
    CommentVicGotFistuleWasReparedSp=models.TextField(max_length=400)
    ObservationsSp=models.BooleanField(default=False,null=True)
    DateVisiTeSp=models.DateField()
    PartenaireRespoSp=models.CharField(max_length=200)

class ReferenceMed(models.Model):
    #reference medicale
    Id_MedRef=models.AutoField(primary_key=True)
    Id_patient=models.OneToOneField(patients,on_delete=CASCADE)
    Date=models.DateField()
    GotAssMedical=models.BooleanField(default=False,null=True)
    TypeAssystanceGot=models.TextField(max_length=200)
    #Examens
    ExamenTestGrossesse=models.BooleanField(default=False,null=True)
    ExamenTestVih=models.BooleanField(default=False,null=True)
    ExamenTestIst=models.BooleanField(default=False,null=True)
    ExamenPhysique=models.BooleanField(default=False,null=True)
    ExamenLabo=models.BooleanField(default=False,null=True)
    If_AssisanceWrittenDoc=models.CharField(max_length=200)
    RapportMedical=models.BooleanField(default=False,null=True)
    AttestationMedical=models.BooleanField(default=False,null=True)
    #traitement
    TrContracepUrgence=models.BooleanField(default=False,null=True)
    TrPreventionVih=models.BooleanField(default=False,null=True)
    TrIst=models.BooleanField(default=False,null=True)
    TrOtherPricise=models.TextField(max_length=200)
    CertificaMedical=models.BooleanField(default=False,null=True)
    If_ExamenMedicauxAfterAgression=models.BooleanField(default=False,null=True)
    ExamenMediAfterAgressionDescript=models.TextField(max_length=400)
    ExamenMediAfterAgressionReasonsIfnon=models.TextField(max_length=400)
    If_GrossesseBeforeViol=models.BooleanField(default=False,null=True)
    If_ConceptionSviol=models.BooleanField(default=False,null=True)
    IF_EnfantOrFoetusalive=models.BooleanField(default=False,null=True)
    SequellOrLesionPhysique=models.TextField(default=False,null=True)
    NomStructure=models.CharField(max_length=200)
    QualiteStrucutre=models.CharField(max_length=200)
    NomClinicien=models.CharField(max_length=200)
    FonctionClinicien=models.CharField(max_length=200)
    DateClini=models.DateField()
    SignatureClini=models.CharField(max_length=255)

class CertificatMed(models.Model):
    #cerfifical medical
    Id_Certificat=models.AutoField(primary_key=True)
    Id_patient=models.OneToOneField(patients,on_delete=CASCADE)
    SigneExamenGeneral=models.TextField(max_length=400)
    SigneExamenPhysiqueGeneral=models.TextField(max_length=400)
    SigneExamenGenital=models.TextField(max_length=400)
    SigneExamenParaDinique=models.TextField(max_length=400)
    SingeEvalueRisqueGrossesse=models.TextField(max_length=400)
    SigneEtatVicSortie=models.TextField(max_length=400)
    SignePronostic=models.TextField(max_length=400)
    SigneCAT=models.TextField(max_length=400)
    SigneConclusion=models.TextField(max_length=400)
    NomClincien=models.CharField(max_length=200)
    SignatureClinicien=models.CharField(max_length=200)
    NomStructure=models.CharField(max_length=200)
    AdressePhysiqueStru=models.CharField(max_length=200)
    NumerotelStructure=models.CharField(max_length=200)
    Email=models.CharField(max_length=200)

class PsychoInfodata(models.Model):
    id_psycho=models.AutoField(primary_key=True)
    #identification structure
    id_patient=models.OneToOneField(patients,on_delete=CASCADE)
    CodeStructure=models.CharField(max_length=200)
    Province=models.CharField(max_length=200)
    Territoire=models.CharField(max_length=200)
    District=models.CharField(max_length=200)
    ZoneDesante=models.CharField(max_length=200)
    DateInscription=models.CharField(max_length=200)
    #identificationde la survivante
    CodeNomLettres=models.CharField(max_length=200)
    Ordre=models.CharField(max_length=200)
    Inc=models.CharField(max_length=200)
    Anne=models.DateField()
    codeZoneSante=models.CharField(max_length=200)
    #infogeneral
    EmotionReaction=models.CharField(max_length=200)
    SameActiviBeforeIncident=models.CharField(max_length=200)
    #prise en charge
    TypeAccomPsycho=models.CharField(max_length=200)
    QualPrestateurCharge=models.CharField(max_length=200)
    If_VicGotSupport=models.BooleanField(default=False,null=True)
    WhatIf_VicHasSupport=models.CharField(max_length=200)
    #suivi
    If_vicHadAppointSuivi=models.BooleanField(default=False,null=True)
    Ifnot_vicHadAppointSuiviWhy=models.CharField(max_length=200)
    If_survivePresentedVist=models.BooleanField(default=False,null=True)
    Ifnot_AbandonTreatement=models.BooleanField(default=False,null=True)
    #reference et contre reference
    RefAndContreRef=models.CharField(max_length=200)
    OtherInfo=models.TextField(max_length=800)
    CodeResponsable=models.CharField(max_length=200)
    FonctionRe=models.CharField(max_length=200)
    Date=models.DateField()
    Signature=models.CharField(max_length=255)

class ConsentemenData(models.Model):
    id_Consentement=models.AutoField(primary_key=True)
    id_patient=models.OneToOneField(patients,on_delete=CASCADE)
    If_insomnie=models.BooleanField(default=False,null=True)
    If_doulAbdomDos=models.BooleanField(default=False,null=True)
    If_culpabilite=models.BooleanField(default=False,null=True)
    if_SousEstimation=models.BooleanField(default=False,null=True)
    If_ArrestaionAgresseur=models.BooleanField(default=False,null=True)
    If_TristeAndDiscourage=models.BooleanField(default=False,null=True)
    If_shame=models.BooleanField(default=False,null=True)
    If_angryOrAgre=models.BooleanField(default=False,null=True)
    If_affraid=models.BooleanField(default=False,null=True)
    Other=models.CharField(max_length=200)
    PriseChargeMedi=models.BooleanField(default=False,null=True)
    PriseChargePsycho=models.BooleanField(default=False,null=True)
    PriseChargeJuri=models.BooleanField(default=False,null=True)


        

