# Generated by Django 3.2.10 on 2021-12-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('postnom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('DateNais', models.DateField()),
                ('provenance', models.CharField(max_length=200)),
                ('sexe', models.CharField(max_length=200)),
                ('nomAccompagnant', models.CharField(max_length=200)),
                ('EtatCivil', models.CharField(max_length=200)),
                ('NiveauEtude', models.CharField(max_length=200)),
                ('ZoneDesante', models.CharField(max_length=200)),
                ('Occupation', models.CharField(max_length=200)),
                ('LieuNaissance', models.CharField(max_length=200)),
                ('DateExamen', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, null=True)),
                ('postnom', models.CharField(max_length=100, null=True)),
                ('Tel', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('photo', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_update', models.DateTimeField()),
            ],
        ),
    ]
