# Generated by Django 3.2.10 on 2021-12-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
